export enum EditorBlockTypes {
  Unstyled = "unstyled",
  Paragraphq = "paragraph",
  HeaderOne = "header-one",
  HeaderTwo = "header-two",
  HeaderThree = "header-three",
  HeaderFour = "header-four",
  HeaderFive = "header-five",
  HeaderSix = "header-six",
  Unordered = "unordered-list-item",
  Ordered = "ordered-list-item",
  Blockquote = "blockquote",
  CodeBlock = "code-block",
  Atomic = "atomic",
  Image = "image",
  Divider = "divider",
  Placeholder = "placeholder",
  Embed = "embed",
}
